import typing
from .bmpto105_data import RGBColor, MSXBitmap_105
from PIL import Image


class BmpTo105:
    def __init__(self, palette: typing.Sequence[tuple[int, int, int]]) -> None: ...
    def convert(self, image: Image.Image) -> MSXBitmap_105: ...
    def get_palette(self) -> list[RGBColor]: ...

class _RGBBitmap:
    def __init__(self, arg0: typing.SupportsInt | typing.SupportsIndex, arg1: typing.SupportsInt | typing.SupportsIndex, arg2: typing.SupportsInt | typing.SupportsIndex, arg3: typing.Sequence[typing.SupportsInt | typing.SupportsIndex]) -> None: ...
    @property
    def data(self) -> list[int]: ...
    @property
    def height(self) -> int: ...
    @property
    def width(self) -> int: ...
